steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Step 1 - Show current directory
    run: pwd

  - name: Step 2 - List files
    run: ls -al

  - name: Step 3 - Print custom message
    run: echo "CI Pipeline Running Successfully!"
